name: Run CANoe Tests on Ino Change

on:
  push:
    paths:
      - 'Arduino/ACC_project.ino'

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Python script with CANoe
      run: python ACC_Arduino/Python/RunAllTests_modified.py
