
name: Run Python Tests on Arduino File Change

on:
  push:
    paths:
      - 'Arduino/ACC_project.ino'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies (optional)
      run: |
        python -m pip install --upgrade pip
        # Add your requirements if needed
        # pip install -r ACC_Arduino/Python/requirements.txt

    - name: Run Python test script
      run: python ACC_Arduino/Python/RunAllTests_modified.py
